name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLOUDTASKMANAGERAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CLOUDTASKMANAGERAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CLOUDTASKMANAGERAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile
          registryUrl: ${{ secrets.CLOUDTASKMANAGERAPI_REGISTRY_URL }}
          registryUsername: ${{ secrets.CLOUDTASKMANAGERAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CLOUDTASKMANAGERAPI_REGISTRY_PASSWORD }}
          containerAppName: cloud-task-manager-api
          resourceGroup: cloud-app-rg
          imageToBuild: cloud-task-manager-api:${{ github.sha }}
          targetPort: 8081
